#!/usr/bin/env python3
"""Generate cue_cueshot_pcm.h (decoded 2dpool cueshot.mp3) and
cue_cushion_pcm.h (a faithful render of 2dpool's playRailCollision synth)
as mono 22050 Hz s16 C arrays, matching the existing cue_clack_pcm.h format."""
import numpy as np, subprocess, os

RATE = 22050
SND  = os.path.expanduser("~/2dpool/2dpool/assets/sounds")
OUT  = os.path.expanduser("~/thumby-color/ThumbyCue/game")

def write_header(path, name, macro, data, comment):
    data = np.clip(np.round(data), -32768, 32767).astype(np.int16)
    with open(path, "w") as f:
        f.write(comment + "\n")
        f.write(f"#ifndef {macro}_H\n#define {macro}_H\n#include <stdint.h>\n")
        f.write(f"#define {macro}_LEN {len(data)}\n")
        f.write(f"static const int16_t {name}[{macro}_LEN] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ",".join(str(int(v)) for v in data[i:i+16]) + ",\n")
        f.write("};\n#endif\n")
    print(f"wrote {path}  ({len(data)} samples, {len(data)/RATE*1000:.0f} ms)")

# ---- cue strike: decode the real 2dpool cueshot.mp3 ----------------------
raw = subprocess.run(
    ["ffmpeg","-v","quiet","-i",f"{SND}/cueshot.mp3",
     "-ac","1","-ar",str(RATE),"-f","s16le","-"],
    capture_output=True).stdout
shot = np.frombuffer(raw, dtype=np.int16).astype(np.float64)
# trim leading/trailing near-silence so the click fires tight on the strike
thr = 0.01 * 32768
nz  = np.where(np.abs(shot) > thr)[0]
if len(nz): shot = shot[nz[0]:nz[-1]+1]
peak = np.max(np.abs(shot)) or 1.0
shot = shot * (30000.0 / peak)        # normalise hot; gain is applied at play time
write_header(f"{OUT}/cue_cueshot_pcm.h", "cue_cueshot_pcm", "CUE_CUESHOT_PCM", shot,
    "/* Cue-tip strike, cueshot.mp3 (2dpool), mono 22050 Hz s16.\n"
    " * Auto-generated from assets/sounds/cueshot.mp3 — do not hand-edit. */")

# ---- cushion: render 2dpool playRailCollision (3-layer synth) ------------
# RBJ cookbook biquads, matching Web Audio BiquadFilterNode.
def biquad(x, kind, f, Q):
    w0 = 2*np.pi*f/RATE; cw = np.cos(w0); sw = np.sin(w0); al = sw/(2*Q)
    if kind == "lp":
        b0=(1-cw)/2; b1=1-cw; b2=(1-cw)/2; a0=1+al; a1=-2*cw; a2=1-al
    else:  # bandpass (constant 0 dB peak)
        b0=al; b1=0; b2=-al; a0=1+al; a1=-2*cw; a2=1-al
    b0/=a0; b1/=a0; b2/=a0; a1/=a0; a2/=a0
    y=np.zeros_like(x); x1=x2=y1=y2=0.0
    for n in range(len(x)):
        xn=x[n]; yn=b0*xn+b1*x1+b2*x2-a1*y1-a2*y2
        x2=x1; x1=xn; y2=y1; y1=yn; y[n]=yn
    return y

def env_exp(n, T, v0, vend=0.001):
    t=np.arange(n)/RATE; T=max(T,1e-4)
    return v0*np.power(vend/v0, np.clip(t/T,0,1))

intensity = 0.65                      # representative hit (layer-3 resonance present)
vol = 0.12 + intensity*0.18
N = int(0.16*RATE)
rng = np.random.default_rng(7)
out = np.zeros(N)

# Layer 1: soft rubber thud — noise -> lowpass(600) -> bandpass(200,Q1)
n1=int(0.10*RATE); nz1=rng.uniform(-1,1,n1)
y1=biquad(biquad(nz1,"lp",600,0.707),"bp",200,1.0)
out[:n1]+=y1*env_exp(n1,0.08,vol*0.7)

# Layer 2: subtle high contact — noise -> bandpass(1200,Q3)
n2=int(0.03*RATE); nz2=rng.uniform(-1,1,n2)
y2=biquad(nz2,"bp",1200,3.0)
out[:n2]+=y2*env_exp(n2,0.025,vol*0.25)

# Layer 3: table resonance — sine 106->50 Hz, exp freq ramp
n3=int(0.15*RATE); t=np.arange(n3)/RATE; Tf=0.12
f0=80+intensity*40; fr=f0*np.power(50.0/f0,np.clip(t/Tf,0,1))
phase=2*np.pi*np.cumsum(fr)/RATE
out[:n3]+=np.sin(phase)*env_exp(n3,0.12,vol*0.15*intensity)

peak=np.max(np.abs(out)) or 1.0
out=out*(26000.0/peak)                # normalise; per-hit gain applied at play time
write_header(f"{OUT}/cue_cushion_pcm.h", "cue_cushion_pcm", "CUE_CUSHION_PCM", out,
    "/* Rail/cushion thud — faithful render of 2dpool playRailCollision\n"
    " * (3-layer synth: rubber thud + high contact + table resonance),\n"
    " * mono 22050 Hz s16. Auto-generated by tools/gen_cue_sounds.py. */")

# ---- pocket: decode the three 2dpool pot recordings ----------------------
# playPocket: pool -> pot.mp3; snooker -> softpot.mp3 / hardpot.mp3 (split 4 m/s)
def decode_pot(mp3, name, macro, src):
    raw = subprocess.run(
        ["ffmpeg","-v","quiet","-i",f"{SND}/{mp3}",
         "-ac","1","-ar",str(RATE),"-f","s16le","-"],
        capture_output=True).stdout
    x = np.frombuffer(raw, dtype=np.int16).astype(np.float64)
    nz = np.where(np.abs(x) > 0.008*32768)[0]      # trim leading/trailing silence
    if len(nz): x = x[nz[0]:nz[-1]+1]
    peak = np.max(np.abs(x)) or 1.0
    x = x * (30000.0 / peak)                        # normalise; gain at play time
    write_header(f"{OUT}/{name}_pcm.h", f"{name}_pcm", macro, x,
        f"/* {src} pocket sound, {mp3} (2dpool), mono 22050 Hz s16.\n"
        f" * Auto-generated from assets/sounds/{mp3} — do not hand-edit. */")

decode_pot("pot.mp3",     "cue_pot",     "CUE_POT",     "Pool")
decode_pot("softpot.mp3", "cue_softpot", "CUE_SOFTPOT", "Snooker soft")
decode_pot("hardpot.mp3", "cue_hardpot", "CUE_HARDPOT", "Snooker hard")
